name: .NET Core CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore StudentPlanner.Api/StudentPlanner.Api.sln

    - name: Build
      run: dotnet build StudentPlanner.Api/StudentPlanner.Api.sln --no-restore

    - name: Test
      run: dotnet test StudentPlanner.Api/StudentPlanner.Api.sln --no-build --verbosity normal
